"""
Template field definitions for all 6 template types.

Loads field definitions from the canonical source: scripts/field_row_mappings.json
This JSON is generated by scripts/generate_field_row_mapping.py from the standardized
Google Sheets templates.

Each field has:
- row: Row number in the Google Sheet
- section: Section grouping (SEO, Hero, About, etc.)
- char_limit: Maximum character count (None = no limit)
- required: Whether field must have content before publish
- field_type: GENERATED (LLM creates), EXTRACTED (from PDF), HYBRID, or STATIC

Source of truth: scripts/field_row_mappings.json (549 fields across 6 templates)
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Optional


class FieldType(str, Enum):
    """Classification of how a field gets its content."""
    GENERATED = "GENERATED"  # LLM generates content
    EXTRACTED = "EXTRACTED"  # Pulled directly from source PDF
    HYBRID = "HYBRID"        # LLM enhances extracted data
    STATIC = "STATIC"        # Fixed/template value


@dataclass(frozen=True)
class FieldDef:
    """Definition of a single template field."""
    row: int                              # Row number in Google Sheet
    section: str                          # Section name (SEO, Hero, About, etc.)
    char_limit: Optional[int] = None      # Max characters, None = no limit
    required: bool = False                # Whether field must have content
    field_type: FieldType = FieldType.GENERATED

    @property
    def character_limit(self) -> Optional[int]:
        """Alias for char_limit for backward compatibility."""
        return self.char_limit


# Type alias for field registries
FieldRegistry = dict[str, FieldDef]


def _load_field_mappings() -> dict[str, FieldRegistry]:
    """Load field definitions from JSON file."""
    # Path relative to this module
    json_path = Path(__file__).parent.parent.parent / "scripts" / "field_row_mappings.json"

    if not json_path.exists():
        raise FileNotFoundError(
            f"Field mappings not found at {json_path}. "
            f"Run: python scripts/generate_field_row_mapping.py"
        )

    with open(json_path, "r", encoding="utf-8") as f:
        raw_data = json.load(f)

    registry: dict[str, FieldRegistry] = {}

    for template_type, fields in raw_data.items():
        template_fields: FieldRegistry = {}
        for field_name, field_data in fields.items():
            template_fields[field_name] = FieldDef(
                row=field_data["row"],
                section=field_data["section"],
                char_limit=field_data.get("char_limit"),
                required=field_data.get("required", False),
                field_type=FieldType(field_data.get("field_type", "GENERATED")),
            )
        registry[template_type] = template_fields

    return registry


# Load at module initialization
TEMPLATE_FIELD_REGISTRY: dict[str, FieldRegistry] = _load_field_mappings()

# Individual template exports for backward compatibility
AGGREGATORS_FIELDS: FieldRegistry = TEMPLATE_FIELD_REGISTRY.get("aggregators", {})
OPR_FIELDS: FieldRegistry = TEMPLATE_FIELD_REGISTRY.get("opr", {})
MPP_FIELDS: FieldRegistry = TEMPLATE_FIELD_REGISTRY.get("mpp", {})
ADOP_FIELDS: FieldRegistry = TEMPLATE_FIELD_REGISTRY.get("adop", {})
ADRE_FIELDS: FieldRegistry = TEMPLATE_FIELD_REGISTRY.get("adre", {})
COMMERCIAL_FIELDS: FieldRegistry = TEMPLATE_FIELD_REGISTRY.get("commercial", {})


def get_fields_for_template(template_type: str) -> FieldRegistry:
    """
    Get field definitions for a template type.

    Args:
        template_type: One of: aggregators, opr, mpp, adop, adre, commercial

    Returns:
        Dict mapping field_name -> FieldDef

    Raises:
        ValueError: If template_type is not recognized
    """
    template_key = template_type.lower()
    if template_key not in TEMPLATE_FIELD_REGISTRY:
        raise ValueError(
            f"Unknown template type: {template_type}. "
            f"Valid types: {list(TEMPLATE_FIELD_REGISTRY.keys())}"
        )
    return TEMPLATE_FIELD_REGISTRY[template_key]


def get_cell_mapping(template_type: str, language: str = "en") -> dict[str, str]:
    """
    Build field_name -> cell_reference mapping for a template.

    Column offsets: C=EN, D=AR, E=RU
    (Column A = Guidelines, Column B = Field Label)

    Args:
        template_type: One of the 6 template types
        language: "en", "ar", or "ru"

    Returns:
        Dict mapping field names to cell references (e.g., {"meta_title": "C4"})

    Raises:
        ValueError: If language is not supported
    """
    col_map = {"en": "C", "ar": "D", "ru": "E"}
    col = col_map.get(language.lower())
    if col is None:
        raise ValueError(f"Unsupported language: {language}. Valid: en, ar, ru")

    fields = get_fields_for_template(template_type)
    return {name: f"{col}{field.row}" for name, field in fields.items()}


def get_sections_for_template(template_type: str) -> dict[str, list[str]]:
    """
    Get fields grouped by section for a template.

    Returns:
        {"SEO": ["meta_title", "meta_description", ...], "Hero": [...], ...}
        Preserves insertion order (field order within section matches row order).
    """
    fields = get_fields_for_template(template_type)
    sections: dict[str, list[str]] = {}
    for name, field in fields.items():
        sections.setdefault(field.section, []).append(name)
    return sections


def get_character_limit(template_type: str, field_name: str) -> Optional[int]:
    """
    Get character limit for a specific field.

    Convenience function for backward compatibility with code that
    expects dict[str, Optional[int]] format.

    Args:
        template_type: Template type
        field_name: Field name

    Returns:
        Character limit or None if no limit
    """
    fields = get_fields_for_template(template_type)
    field_def = fields.get(field_name)
    return field_def.char_limit if field_def else None


def get_required_fields(template_type: str) -> list[str]:
    """Get list of required field names for a template."""
    fields = get_fields_for_template(template_type)
    return [name for name, field in fields.items() if field.required]


def get_generated_fields(template_type: str) -> list[str]:
    """Get list of field names that require LLM generation."""
    fields = get_fields_for_template(template_type)
    return [
        name for name, field in fields.items()
        if field.field_type in (FieldType.GENERATED, FieldType.HYBRID)
    ]


# Module-level validation
def _validate_registry():
    """Validate that all templates loaded correctly."""
    expected = {"aggregators", "opr", "mpp", "adop", "adre", "commercial"}
    loaded = set(TEMPLATE_FIELD_REGISTRY.keys())
    if loaded != expected:
        missing = expected - loaded
        extra = loaded - expected
        raise RuntimeError(
            f"Template registry validation failed. "
            f"Missing: {missing}, Extra: {extra}"
        )

    # Verify minimum field counts
    min_counts = {
        "aggregators": 100,
        "opr": 100,
        "mpp": 80,
        "adop": 50,
        "adre": 100,
        "commercial": 60,
    }
    for template_type, min_count in min_counts.items():
        actual = len(TEMPLATE_FIELD_REGISTRY[template_type])
        if actual < min_count:
            raise RuntimeError(
                f"{template_type} has {actual} fields, expected >= {min_count}"
            )


# Run validation on import
_validate_registry()
