"""add sequence column to job_steps

Revision ID: 301c11af3c4e
Revises: 004_fix_constraints
Create Date: 2026-02-04 13:04:27.916685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '301c11af3c4e'
down_revision: Union[str, None] = '004_fix_constraints'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_execution_history_created_at', table_name='execution_history')
    op.create_index('idx_execution_history_created_at', 'execution_history', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_constraint('execution_history_user_id_fkey', 'execution_history', type_='foreignkey')
    op.create_foreign_key(None, 'execution_history', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_generated_content_project_template', 'generated_content', ['project_id', 'template_type', 'content_variant'], unique=False)
    op.drop_constraint('generated_content_prompt_version_id_fkey', 'generated_content', type_='foreignkey')
    op.drop_constraint('generated_content_approved_by_fkey', 'generated_content', type_='foreignkey')
    op.create_foreign_key(None, 'generated_content', 'users', ['approved_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'generated_content', 'prompt_versions', ['prompt_version_id'], ['id'], ondelete='SET NULL')
    op.add_column('job_steps', sa.Column('sequence', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.create_index('idx_job_steps_job_step', 'job_steps', ['job_id', 'step_id'], unique=True)
    op.drop_index('idx_jobs_completed_at', table_name='jobs')
    op.create_index('idx_jobs_completed_at', 'jobs', ['completed_at'], unique=False, postgresql_ops={'completed_at': 'DESC'})
    op.drop_index('idx_jobs_created_at', table_name='jobs')
    op.create_index('idx_jobs_created_at', 'jobs', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_constraint('jobs_user_id_fkey', 'jobs', type_='foreignkey')
    op.drop_constraint('jobs_template_id_fkey', 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'jobs', 'templates', ['template_id'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_notifications_created_at', table_name='notifications')
    op.create_index('idx_notifications_created_at', 'notifications', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_notifications_user_feed', 'notifications', ['user_id', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index('idx_project_approvals_created_at', table_name='project_approvals')
    op.create_index('idx_project_approvals_created_at', 'project_approvals', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_constraint('project_approvals_approver_id_fkey', 'project_approvals', type_='foreignkey')
    op.create_foreign_key(None, 'project_approvals', 'users', ['approver_id'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_project_revisions_created_at', table_name='project_revisions')
    op.create_index('idx_project_revisions_created_at', 'project_revisions', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_constraint('project_revisions_changed_by_fkey', 'project_revisions', type_='foreignkey')
    op.create_foreign_key(None, 'project_revisions', 'users', ['changed_by'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_projects_created_at', table_name='projects')
    op.create_index('idx_projects_created_at', 'projects', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.drop_index('idx_projects_search', table_name='projects', postgresql_using='gin')
    op.create_index('idx_projects_search', 'projects', [sa.text("to_tsvector('english', coalesce(name, '') || ' ' || coalesce(developer, '') || ' ' || coalesce(location, '') || ' ' || coalesce(description, ''))")], unique=False, postgresql_using='gin')
    op.drop_constraint('projects_created_by_fkey', 'projects', type_='foreignkey')
    op.drop_constraint('projects_last_modified_by_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['last_modified_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_prompt_versions_created_at', table_name='prompt_versions')
    op.create_index('idx_prompt_versions_created_at', 'prompt_versions', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index('idx_prompt_versions_version', table_name='prompt_versions')
    op.create_index('idx_prompt_versions_version', 'prompt_versions', ['prompt_id', 'version'], unique=False, postgresql_ops={'version': 'DESC'})
    op.create_unique_constraint('uq_prompt_version_per_prompt', 'prompt_versions', ['prompt_id', 'version'])
    op.drop_constraint('prompt_versions_created_by_fkey', 'prompt_versions', type_='foreignkey')
    op.create_foreign_key(None, 'prompt_versions', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_index('idx_prompts_lookup', 'prompts', ['template_type', 'content_variant', 'name', 'is_active'], unique=False)
    op.drop_constraint('prompts_updated_by_fkey', 'prompts', type_='foreignkey')
    op.drop_constraint('prompts_created_by_fkey', 'prompts', type_='foreignkey')
    op.create_foreign_key(None, 'prompts', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'prompts', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('publication_checklists', 'items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=False)
    op.drop_constraint('qa_checkpoints_checked_by_fkey', 'qa_checkpoints', type_='foreignkey')
    op.create_foreign_key(None, 'qa_checkpoints', 'users', ['checked_by'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_qa_comparisons_performed_at', table_name='qa_comparisons')
    op.create_index('idx_qa_comparisons_performed_at', 'qa_comparisons', ['performed_at'], unique=False, postgresql_ops={'performed_at': 'DESC'})
    op.drop_constraint('qa_comparisons_performed_by_fkey', 'qa_comparisons', type_='foreignkey')
    op.create_foreign_key(None, 'qa_comparisons', 'users', ['performed_by'], ['id'], ondelete='SET NULL')
    op.create_index('idx_qa_issues_project_unresolved', 'qa_issues', ['project_id', 'is_resolved'], unique=False)
    op.drop_constraint('qa_issues_resolved_by_fkey', 'qa_issues', type_='foreignkey')
    op.create_foreign_key(None, 'qa_issues', 'users', ['resolved_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint('qa_overrides_overridden_by_fkey', 'qa_overrides', type_='foreignkey')
    op.create_foreign_key(None, 'qa_overrides', 'users', ['overridden_by'], ['id'], ondelete='SET NULL')
    op.alter_column('templates', 'field_mappings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_google_id', table_name='users')
    op.create_unique_constraint('uq_workflow_items_project_id', 'workflow_items', ['project_id'])
    op.drop_constraint('workflow_items_assigned_to_fkey', 'workflow_items', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_items', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_items', type_='foreignkey')
    op.create_foreign_key('workflow_items_assigned_to_fkey', 'workflow_items', 'users', ['assigned_to'], ['id'])
    op.drop_constraint('uq_workflow_items_project_id', 'workflow_items', type_='unique')
    op.create_index('idx_users_google_id', 'users', ['google_id'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.alter_column('templates', 'field_mappings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(None, 'qa_overrides', type_='foreignkey')
    op.create_foreign_key('qa_overrides_overridden_by_fkey', 'qa_overrides', 'users', ['overridden_by'], ['id'])
    op.drop_constraint(None, 'qa_issues', type_='foreignkey')
    op.create_foreign_key('qa_issues_resolved_by_fkey', 'qa_issues', 'users', ['resolved_by'], ['id'])
    op.drop_index('idx_qa_issues_project_unresolved', table_name='qa_issues')
    op.drop_constraint(None, 'qa_comparisons', type_='foreignkey')
    op.create_foreign_key('qa_comparisons_performed_by_fkey', 'qa_comparisons', 'users', ['performed_by'], ['id'])
    op.drop_index('idx_qa_comparisons_performed_at', table_name='qa_comparisons', postgresql_ops={'performed_at': 'DESC'})
    op.create_index('idx_qa_comparisons_performed_at', 'qa_comparisons', [sa.text('performed_at DESC')], unique=False)
    op.drop_constraint(None, 'qa_checkpoints', type_='foreignkey')
    op.create_foreign_key('qa_checkpoints_checked_by_fkey', 'qa_checkpoints', 'users', ['checked_by'], ['id'])
    op.alter_column('publication_checklists', 'items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(None, 'prompts', type_='foreignkey')
    op.drop_constraint(None, 'prompts', type_='foreignkey')
    op.create_foreign_key('prompts_created_by_fkey', 'prompts', 'users', ['created_by'], ['id'])
    op.create_foreign_key('prompts_updated_by_fkey', 'prompts', 'users', ['updated_by'], ['id'])
    op.drop_index('idx_prompts_lookup', table_name='prompts')
    op.drop_constraint(None, 'prompt_versions', type_='foreignkey')
    op.create_foreign_key('prompt_versions_created_by_fkey', 'prompt_versions', 'users', ['created_by'], ['id'])
    op.drop_constraint('uq_prompt_version_per_prompt', 'prompt_versions', type_='unique')
    op.drop_index('idx_prompt_versions_version', table_name='prompt_versions', postgresql_ops={'version': 'DESC'})
    op.create_index('idx_prompt_versions_version', 'prompt_versions', ['prompt_id', sa.text('version DESC')], unique=False)
    op.drop_index('idx_prompt_versions_created_at', table_name='prompt_versions', postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_prompt_versions_created_at', 'prompt_versions', [sa.text('created_at DESC')], unique=False)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_last_modified_by_fkey', 'projects', 'users', ['last_modified_by'], ['id'])
    op.create_foreign_key('projects_created_by_fkey', 'projects', 'users', ['created_by'], ['id'])
    op.drop_index('idx_projects_search', table_name='projects', postgresql_using='gin')
    op.create_index('idx_projects_search', 'projects', [sa.text("to_tsvector('english'::regconfig, (((((COALESCE(name, ''::character varying)::text || ' '::text) || COALESCE(developer, ''::character varying)::text) || ' '::text) || COALESCE(location, ''::character varying)::text) || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_index('idx_projects_created_at', table_name='projects', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_projects_created_at', 'projects', [sa.text('created_at DESC')], unique=False)
    op.drop_constraint(None, 'project_revisions', type_='foreignkey')
    op.create_foreign_key('project_revisions_changed_by_fkey', 'project_revisions', 'users', ['changed_by'], ['id'])
    op.drop_index('idx_project_revisions_created_at', table_name='project_revisions', postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_project_revisions_created_at', 'project_revisions', [sa.text('created_at DESC')], unique=False)
    op.drop_constraint(None, 'project_approvals', type_='foreignkey')
    op.create_foreign_key('project_approvals_approver_id_fkey', 'project_approvals', 'users', ['approver_id'], ['id'])
    op.drop_index('idx_project_approvals_created_at', table_name='project_approvals', postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_project_approvals_created_at', 'project_approvals', [sa.text('created_at DESC')], unique=False)
    op.drop_index('idx_notifications_user_feed', table_name='notifications', postgresql_ops={'created_at': 'DESC'})
    op.drop_index('idx_notifications_created_at', table_name='notifications', postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_notifications_created_at', 'notifications', [sa.text('created_at DESC')], unique=False)
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key('jobs_template_id_fkey', 'jobs', 'templates', ['template_id'], ['id'])
    op.create_foreign_key('jobs_user_id_fkey', 'jobs', 'users', ['user_id'], ['id'])
    op.drop_index('idx_jobs_created_at', table_name='jobs', postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_jobs_created_at', 'jobs', [sa.text('created_at DESC')], unique=False)
    op.drop_index('idx_jobs_completed_at', table_name='jobs', postgresql_ops={'completed_at': 'DESC'})
    op.create_index('idx_jobs_completed_at', 'jobs', [sa.text('completed_at DESC')], unique=False)
    op.drop_index('idx_job_steps_job_step', table_name='job_steps')
    op.drop_column('job_steps', 'sequence')
    op.drop_constraint(None, 'generated_content', type_='foreignkey')
    op.drop_constraint(None, 'generated_content', type_='foreignkey')
    op.create_foreign_key('generated_content_approved_by_fkey', 'generated_content', 'users', ['approved_by'], ['id'])
    op.create_foreign_key('generated_content_prompt_version_id_fkey', 'generated_content', 'prompt_versions', ['prompt_version_id'], ['id'])
    op.drop_index('idx_generated_content_project_template', table_name='generated_content')
    op.drop_constraint(None, 'execution_history', type_='foreignkey')
    op.create_foreign_key('execution_history_user_id_fkey', 'execution_history', 'users', ['user_id'], ['id'])
    op.drop_index('idx_execution_history_created_at', table_name='execution_history', postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_execution_history_created_at', 'execution_history', [sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###
